export const DEFAULT_COLORS: string[] = [
  "#000000",
  "#808080",
  "#800100",
  "#808000",
  "#008000",
  "#038080",
  "#0E0080",
  "#800180",
  "#7F8040",
  "#014040",
  "#0180FF",
  "#004080",
  "#4002FF",
  "#804000",
  "#FFFFFF",
  "#C0C0C0",
  "#FF0000",
  "#FFFF00",
  "#00FF00",
  "#00FFFF",
  "#0000FF",
  "#FF00FF",
  "#FFFF0F",
  "#00FF0F",
  "#0FFFFF",
  "#0F0FFF",
  "#FF000F",
  "#FF8040",
];

export const AVAILABLE_TOOLS = [
  {
    label: "selection-free",
    src: "src/assets/tools/free-select.png",
    alt: "Free form selection tool",
  },
  {
    label: "selection-rect",
    src: "src/assets/tools/rect-select.png",
    alt: "Rectangular selection tool",
  },
  { label: "eraser", src: "src/assets/tools/eraser.png", alt: "Eraser tool" },
  {
    label: "paint-bucket",
    src: "src/assets/tools/paint-bucker.png",
    alt: "Paint bucket tool",
  },
  {
    label: "color-picker",
    src: "src/assets/tools/color-picker.png",
    alt: "Color picker tool",
  },
  { label: "zoom", src: "src/assets/tools/zoom.png", alt: "Zooming tool" },
  { label: "pencil", src: "src/assets/tools/pencil.png", alt: "Pencil tool" },
  {
    label: "brush",
    src: "src/assets/tools/paint-brush.png",
    alt: "Paint brush tool",
  },
  {
    label: "graphiti",
    src: "src/assets/tools/grafiti.png",
    alt: "Graphiti tool",
  },
  { label: "text", src: "src/assets/tools/text.png", alt: "Text tool" },
  { label: "line", src: "src/assets/tools/line.png", alt: "Line tool" },
  {
    label: "curve",
    src: "src/assets/tools/bezzier.png",
    alt: "Bezzier curve tool",
  },
  {
    label: "rect",
    src: "src/assets/tools/rectangle.png",
    alt: "Rectangle tool",
  },
  { label: "shape", src: "src/assets/tools/shape.png", alt: "Shape tool" },
  {
    label: "ellipse",
    src: "src/assets/tools/ellipse.png",
    alt: "Ellipse tool",
  },
  {
    label: "rounded-rect",
    src: "src/assets/tools/rounded-rect.png",
    alt: "Rounded rectangle tool",
  },
];
